# Generated by Django 3.0.4 on 2020-03-09 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20200309_1541'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentpost',
            options={'verbose_name_plural': 'ContentPost'},
        ),
    ]
