# Generated by Django 3.0.4 on 2020-03-09 20:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20200309_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='text',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ContentPost',
        ),
    ]
